export './SplashView/SplashView.dart';
export './bottomNavBar/bottom_nav_bar_view.dart';
export './Auth/login/loginView.dart';
export './Auth/register/registerView.dart';
export './Home/HomeView.dart';
export './onBoard/onBoardScreen.dart';
export './TravelDetails/TravelDetails.dart';
export './Profile/ProfileView.dart';
export './Chat/chat_consultancy.dart';
export './Favourite/favourite_view.dart';
export './Category View/category_view.dart';